### ISSUE TITLE
Suggestion for Stat Block import

### ISSUE THREAD

**Issue by JackDCondon** [cyface/foundryvtt-dcc#4]
Crome PDF veiwer and adobe deal with formatting as described in the book when grabbing text. 

Doing some basic filtering before applying the selection logic could be could to support direct copy and paste from Goodman m Games PDF content. 

![image](https://user-images.githubusercontent.com/7128239/87240593-1f573400-c45e-11ea-96ed-612d503df3d8.png)
This is standard output from a PDF book- it has the CR and LF (or \n and \r i think?) tags because of the books formatting

![image](https://user-images.githubusercontent.com/7128239/87240607-3d249900-c45e-11ea-9b60-3aa776e95f6c.png)
Formatting seen here. 

I tried to edit the code, but im not very skilled at javascript. 

export function parseNPC(npcString) {
    let npc = {};
npcString = npcString.replace("\n", " ");
	npcString = npcString.replace("\r", "");
    npc.name = npcString.replace(/(.*):.*/, "$1").replace(/ ?\(\d+\)/, "");
    npc["data.attributes.init.value"] = npcString.replace(/.*Init ?(.+?);.*/, "$1");

I could not get this to work, so i may be missing something- but taking it into notepad ++ and removing the CR and LF manually does the trick!

**Comment by cyface** [comment]
@JackDCondon You were very close! You just have to chain the replace statements, otherwise, you are undoing your first replace with the second. :) Thank you for the report!  Should be fixed in master now!

**Comment by JackDCondon** [comment]
I did some more testing and was still getting some errors, it may just be cromes PDF viewer being odd,
but i made the following change and after testing 4 modules it worked just fine with cromes PDR Viewer.

```

//npcString = npcString.replace("\n", "").replace("\r", ""); //OLD CODE
npcString = npcString.replace(/[\n\r]+/g, ' ').replace(/\s{2,}/g,' ').replace(/^\s+|\s+$/,'')  //NEW CODE
```


Credit to 
https://stackoverflow.com/questions/22921242/remove-carriage-return-and-space-from-a-string/22921273
For finding a better solution, this seems to handle the space bars a bit better. 

As an aside @cyface , im going to work out git so i can help out directly and you can accept pull requests directly (if there ok obviously) to help out fix any bugs as i find them. If the codes still trash, i think its still more detailed then a written bug report.

**Comment by cyface** [comment]
@cyface Thank you! I updated to this code in master!
